/**
 * Runtime Performance Budgets
 */
export const PERFORMANCE_BUDGET = {
  MAX_INITIAL_JS_KB: 1300,
  TARGET_INITIAL_JS_KB: 900,
  MAX_IMAGE_TOTAL_KB: 2000,
  TARGET_ROUTE_TRANSITION_MS: 300,
  TARGET_FPS: 120,
  MIN_ACCEPTABLE_FPS: 60,
  MAX_DPR: 2,
};
